### ISSUE TITLE
Multiple issues with new update

### ISSUE THREAD

**Issue by Monsieur14** [ravignir/Brave-New-World#2]
Unciv desktop AND Android version 4.1.1-patch2
Last BNW mod version 2022-05-21 13:39
Multiple warnings messages when selecting the mod for a new game : 

- [ ] Warning: Feitora has an empty 'terrainsCanBeBuiltOn'
- [ ] Warning: Venice's unique "+100% Gold in Capital" is deprectated as of 3.17.10
- [ ] Warning: Heroism's unique "Bonus for units in 2 tile radius 15%" is deprecated as of 4.1.0
- [ ] One more bug isn't listed in the error's message. Each time I select BNW in the mods's list, it automatically selects Poland as my starting civ. Annoying but not critical I'd say.

See screenchot attached for more details.
![Unciv_BNW](https://user-images.githubusercontent.com/67506137/169690441-10351318-3620-4356-b697-63a1e8ddfa2a.jpg)

**Comment by ravignir** [comment]
fixed
