### ISSUE TITLE
Doesn't work ?

### ISSUE THREAD

**Issue by Takfeega** [ravignir/Brave-New-World#3]
The mod gives me no errors when I select the mod, but I see no new Civs, resources, policies etc.
Only the building "Borubudur" and "Prora" seem to be present, as well the unit "Future soldier".
I would like to know of this is because of some issue or just because the mod is in an early stage of development.

**Comment by ravignir** [comment]
try again, it should work.

**Comment by Takfeega** [comment]
Now everything works, thanks for the help.
