### ISSUE TITLE
Getting a bunch of errors?

### ISSUE THREAD

**Issue by CthulhuHalo** [ravignir/Brave-New-World#5]
I don't even know where to start with this.
![Screenshot_20221112-161723](https://user-images.githubusercontent.com/44953290/201495030-e6a7126c-786d-4e3a-bccd-3fd8505bb3ba.png)

**Comment by Kuldebar** [comment]
My errors went away with the latest game update (I play on chromebook linux environment" Unciv Version: 4.2.19

Before I was getting errors galore - but that was also when I was using the Android Version on my chromebook. 
.

**Comment by CthulhuHalo** [comment]
I'm running the android version on Android
